---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ledger-api-secret
  namespace: payments
spec:
  encryptedData:
    DB_PASSWORD: AgAZaLFL6KdIYQFDHf+ZdqCL++K8eljxcXdLKs+E2kTdC7O+aBlYh1zaqI0hpx46D6VuTs8JirFTPFOeZyGUNNhHIgzE4hhhlDoa8ocS5bbB/NxcH4NjfOO5tpNUhWVCToRMiMEWR7AZEPHk0DGOBSnhdN+HWVec7+kW3ToA6RkIHu5jkydR8gvAfUhwfJfOln38TLNhyIK/Bp6G0q/BpY55gErtiy0lUuYbq/dPQHn3UP2B0u8fG+0dHmM4TwVdMdrUeRMfHO6VJWNMfCi5GWPZoqLtKOQvZ/PPw4KDPSavsao6ujigZuziNXzI8y2XriuniKgBjLSUMkwh1lOWDM/Q6LGMPGkQzjg7hFKRjfR05tKkQ2qrLESI2sVZE7VbBUKN8SArujBD2J3BXWAB6v8chspj594arg5TTOHdo2EAgI8jQg7GYI5lYVMYbzjo8n4hO6N5pDyQmygXUju+hmvxUc2dJfegHOI4QQ4N/NxrOw+ExEZLrYRKaCoQbt9/Wndi+3ArYHyTjU4hmnQqwMVoNUehBPhmDkMfIMPhuPHcJQ0yPe9xKy+zZBfyT4OOcHG3xpec/nIlf9trIFk3O1uXSOx+m+pprJdmHrM+SFH+TuK9JHFLaUH4HgT/6xz+dl1IuhuAsjJUSR2cW8UrstdhTnA9k3Yg5j1TrT+7Wc2Utb0ooZfHVUwqpnVDi5WfJtRR+VKbTwUMU2PLuA==
    STRIPE_API_KEY: AgADEoO/7tekvTDfeFvlSW7717gjjXpq/SNKjw9bbar1lz7edbuRy5LTQBExXZfROpOkuLMF+Lw3jN8q74SPocLdUev1CLi3qb02N61FU8LToIyQb/sGDzpJU3kx/MIUzYdt3lU79Opxlj3NrPx6bods5QPujDI1XEh9kSpdpEWTb7hmIxIyikHmxLuvfTLSfJ1/MOFc+rXHGeTgDXzLTuKzoyEp5HS+FZzSDDTshzXrcW5odj43MWkPG+6vO5x//tQPgM0UKnhBLhMi0H8i+SQQfY8U3FkFvNmwC4a1cV6b1ohwUXXMXolCSXgtYP8DIO98xCvCSCU2Ptocw6XF8KWPhVsaGLpGcbDwxZFm5PR4R0dVFPVo7LfDD2O2jwHJeOFEb7e9Ackp4AvgmCpS0vHU5Cy3ym+/l+r84FmUUzisbrKtyvw2KlfDYFy/ObK2REpKi0HTPffBwc1AlNP9G62BNG85frNVVU5AwykL1KIb7C32szACY5wNc6QAbyAplQ0YFcGr2z5XzbuqcJxa0cv9DoK1dPRiBAzSRxR0bx+v7nL/+CobnrDwacA6yemMEB7r42Op6CnI66Z8MZDpc/HdEuMquqYIV+qveelIdteVQhjPYT/9WBC5sbeqMp0hFi/2gCQlICL54ufLD2o8vSIfnfG7oltv5V80C+qITYOpFUnkHCswZwKNf6C6K+POXCnCb/hAGM5dkpCyXbG6GMgiyzJGxT4vo0DbHurEwg==
  template:
    metadata:
      name: ledger-api-secret
      namespace: payments
    type: Opaque
