name: build

on:
  push:
    branches: [main]
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Semgrep
        run: |
          python3 -m pip install --upgrade pip --quiet
          pip3 install --quiet semgrep

      - name: Run Semgrep
        run: |
          semgrep scan --config p/ci .

      - name: Run Trivy Filesystem Scan
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: fs
          scan-ref: .
          format: table
          exit-code: 1
          severity: HIGH,CRITICAL
          
      - name: Build and push
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          IMAGE=ghcr.io/$OWNER/ledger-api:${{ github.sha }}

          docker build -t "$IMAGE" ./task2/app
          docker push "$IMAGE"